### ISSUE TITLE
Flicker in splash screen

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#18] opened 2018-07-21 11:56 UTC
When starting the application, the splash screen is shown, and then it flickers a bit and is shown again. Not a critical issue, but would be nice to fix.

**Comment by AndreusExx** [comment] 2018-07-24 12:30
I can't reproduce this. What is the model of the phone and Android version?

**Comment by israellevin** [comment] 2018-07-24 12:34
Mine is Redmi note 4X - Android 6.0 MRA58K, but we also see this on Oren's HTC 10.

**Comment by AndreusExx** [comment] 2018-07-25 12:30
Fixed in 865fda715c30a7f726ae6aba3b81bb0fc026ecb8

**Closed** 2018-07-29 12:01 UTC
Labels: bug
